

#import:
# Contexts
# - https://raw.githubusercontent.com/amido/stacks-pipeline-templates/875d45a6e44aeca0ff51db864a24631a81b2cd2c/taskctl/contexts.yml

contexts:
  docsenv:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -e
        - PSModulePath=/app/src/modules        
        - -w
        - /app
        - russellseymour/pandoc-asciidoctor
        - pwsh
        - -NoProfile
        - -Command
    quote: "'"

  powershell_test:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -v
        - /var/run/docker.sock:/var/run/docker.sock
        - -e
        - PSModulePath=/app/src/modules
        - -w
        - /app
        - russellseymour/runner-pwsh:0.0.4
        - pwsh
        - -NoProfile
        - -Command
    quote: "'"

  powershell:
    executable:
      bin: docker
      args:
        - run
        - --env-file envfile
        - --rm
        - -v
        - ${PWD}:/app
        - -v
        - /var/run/docker.sock:/var/run/docker.sock
        - -e
        - PSModulePath=/app/src/modules
        - -w
        - /app
        - russellseymour/runner-pwsh:0.0.4
        - pwsh
        - -NoProfile
        - -Command
    quote: "'"
    before: env | grep -v PATH > envfile

  dotnet:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -v
        - /var/run/docker.sock:/var/run/docker.sock
        - -e
        - PSModulePath=/app/src/modules
        - -w
        - /app
        - russellseymour/runner-pwsh-dotnet:0.0.3
        - pwsh
        - -NoProfile
        - -Command
    quote: "'"    

tasks:

  clean:
    description: Clean the output directory
    command:
      - rm -rf outputs

  _docs:
    description: Build Docs
    context: docsenv
    command:
      - Build-Documentation -BasePath /app -Pdf -Title "Independent Runner" -AttributeFile /app/build/config/pdf-config.ps1
      - Build-Documentation -BasePath /app -MD -MDX

  generate:
    context: powershell
    description: Build the PowerShell module
    command:
      - Build-PowerShellModule -Path /app/src/modules -name AmidoBuild -target /app/outputs/module

  tests:unit:
    context: powershell_test
    description: Run PowerShell unit tests and coverage on the module
    command:
      - /app/build/scripts/Invoke-PesterTests.ps1 -Path /app/src/modules/AmidoBuild -UnitTests -Coverage

  tests:coverage_report:
    context: dotnet
    description: Create HTML report from coverage doc
    command:
      - Invoke-DotNet -Coverage -Pattern pester-coverage.xml -Path /app -Source /app/src/modules/AmidoBuild -Target /app/outputs/tests

  update:dashboard:
    context: powershell
    description: Update the Deployment Dashboard
    command:
      - Update-InfluxDashboard
    # TODO: Currently handled by ADO pipeline var, captured in Story 4122
    # env: 
    #  PUBLISH_RELEASE: $true

  publish:github:
    context: powershell
    description: Publish Release to GitHub
    command:
      - Publish-GitHubRelease -artifactsList "AmidoBuild.psd1","AmidoBuild.psm1","Independent Runner.pdf"
    env:
      generateReleaseNotes: $true

pipelines:

  docs:
    - task: _docs

  tests:
    - task: tests:unit
    - task: tests:coverage_report
      depends_on:
        - tests:unit

  build:
    - task: generate
  
  release:
    - task: update:dashboard
    - task: publish:github
    
  all:
    - task: clean
    - pipeline: docs
      depends_on:
        - clean
    - pipeline: tests
      depends_on:
        - clean
    - pipeline: build
      depends_on:
        - clean
    # NB: `release` is not declared here, as it must be run as a discrete pipeline to ensure tests/etc. are passed.
