import:
- ./build/taskctl/contexts.yaml
- ./build/taskctl/tasks.yaml

pipelines:
  docs:
    - task: _docs

  tests:
    - task: tests:unit
      allow_failure: true
    - task: tests:coverage_report
      depends_on:
        - tests:unit
    - task: tests:fail_on_error
      depends_on:
        - tests:coverage_report

  build:
    - task: setup:environment
    - task: generate
      depends_on:
        - setup:environment

  release:
    - task: setup:environment
    - task: update:dashboard
      depends_on:
        - setup:environment
    - task: publish:github
      depends_on:
        - setup:environment

  all:
    - task: clean
    - pipeline: docs
      depends_on:
        - clean
    - pipeline: tests
      depends_on:
        - clean
    - pipeline: build
      depends_on:
        - clean
    # NB: `release` is not declared here, as it must be run as a discrete pipeline to ensure tests/etc. are passed.
